# Generated by Django 5.1.1 on 2024-09-19 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('idPago', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('pago_realizado', models.DateField(blank=True, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estatus', models.CharField(blank=True, max_length=255, null=True)),
                ('proximo_pago', models.DateField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('curp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumnos.alumno')),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
    ]
