# Generated by Django 5.1.1 on 2024-09-19 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_alter_alumno_telefono'),
        ('pagos', '0002_pago_idclase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='idClase',
        ),
        migrations.AddField(
            model_name='pago',
            name='idInscripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumnos.inscripcion'),
        ),
    ]
