# Generated by Django 5.1.1 on 2024-09-19 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('idClase', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('cupo', models.IntegerField(blank=True, null=True)),
                ('costo', models.FloatField(blank=True, null=True)),
                ('dias', models.JSONField(blank=True, null=True)),
                ('horario', models.JSONField(blank=True, null=True)),
                ('turno', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id_paquete', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('curp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumnos.alumno')),
            ],
            options={
                'db_table': 'paquete',
            },
        ),
        migrations.CreateModel(
            name='PaqueteClases',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateField(blank=True, null=True)),
                ('id_clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.clase')),
                ('id_paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.paquete')),
            ],
            options={
                'db_table': 'paquete_clases',
            },
        ),
    ]
