# Generated by Django 5.1.1 on 2024-09-19 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paquete',
            old_name='id_paquete',
            new_name='idPaquete',
        ),
        migrations.RenameField(
            model_name='paqueteclases',
            old_name='id_clase',
            new_name='idClase',
        ),
        migrations.RenameField(
            model_name='paqueteclases',
            old_name='id_paquete',
            new_name='idPaquete',
        ),
    ]
