# Generated by Django 5.1.1 on 2024-09-22 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_rename_id_paquete_paquete_idpaquete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='cupo',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='turno',
        ),
    ]
