# Generated by Django 5.1.1 on 2024-09-19 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='id_clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.clase'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='curp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumnos.alumno'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='id_clase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clases.clase'),
        ),
    ]
