# Generated by Django 5.1.1 on 2024-09-19 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='id_asistencia',
            new_name='idAsistencia',
        ),
        migrations.RenameField(
            model_name='asistencia',
            old_name='id_clase',
            new_name='idClase',
        ),
        migrations.RenameField(
            model_name='inscripcion',
            old_name='fecha_inscripcion',
            new_name='fechaInscripcion',
        ),
        migrations.RenameField(
            model_name='inscripcion',
            old_name='id_clase',
            new_name='idClase',
        ),
        migrations.RenameField(
            model_name='inscripcion',
            old_name='id_inscripcion',
            new_name='idInscripcion',
        ),
    ]
