# Generated by Django 5.1.1 on 2024-09-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_rename_id_asistencia_asistencia_idasistencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
