# Generated by Django 5.1.1 on 2024-09-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_alter_alumno_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='foto',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
            preserve_default=False,
        ),
    ]
